Homepage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("chat", views.index, name="index"),
    path("send_message/", views.send_message, name="send_message"),
    path("send_reply/", views.send_reply, name="send_reply"),
    path("like/<int:message_id>/<str:type>/", views.like, name="like"),
]

IPEC_ChatterBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("Homepage.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

Homepage/models.py
from django.db import models


class User(models.Model):
    uid = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.uid


class Message(models.Model):
    text = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.author.uid + " : " + self.text


class Reply(models.Model):
    text = models.TextField(max_length=500)
    original_message = models.ForeignKey(Message, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    is_author = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.author.uid + " : " + self.text

Homepage/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
import random
from .models import User, Message, Reply


def index(request):
    messages = Message.objects.all().order_by("time")
    context = {
        "messages": messages,
    }
    return render(request, "Homepage/index.html", context)


# Create your views here.
def homepage(request):
    if not request.session.session_key:
        request.session.create()

    return redirect(reverse("index") + "#home")
    # return render(request, "Homepage/index.html", context)


def send_message(request):
    if not request.session.session_key:
        request.session.create()
    uid = str(request.session.session_key)[0:3]
    try:
        user = User.objects.get(uid=uid)
    except User.DoesNotExist:
        user = User.objects.create(
            uid=uid,
            gender=random.choice(["male", "female"]),
            name="anon",
        )

    text = request.POST["message"]
    if len(text) > 0:
        message = Message.objects.create(author=user)
        message.text = text
        message.save()

    return redirect(reverse("index") + "#home")


def send_reply(request):
    uid = str(request.session.session_key)[0:3]
    try:
        user = User.objects.get(uid=uid)
    except User.DoesNotExist:
        user = User.objects.create(
            uid=uid,
            gender=random.choice(["male", "female"]),
            name="anon",
        )

    text = request.POST["reply"]
    id = request.POST["original_message"]
    if len(text) > 0:
        message = Message.objects.get(id=id)
        reply = Reply.objects.create(author=user, original_message=message)
        reply.text = text
        reply.save()

    return redirect(reverse("index") + f"#m{id}")


def like(request, message_id, type):
    if type == "message":
        message = Message.objects.get(id=message_id)
        message.likes += 1
        message.save()
        id = f"#m{message_id}"
    else:
        reply = Reply.objects.get(id=message_id)
        reply.likes += 1
        reply.save()
        id = f"#r{message_id}"
    return redirect(reverse("index") + f"{id}")

Homepage/templates/Homepage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" href={% static "Homepage/icon.png" %}>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script>
            $(document).ready(function () {
                // Set focus on the text-box on page load
                $("#text-box").focus();
                
                // Your existing click event handler
                $(".fa-reply").on("click", function () {
                    // Toggle the visibility of the closest text box
                    $(this).closest('.comment-box').find('.reply-text-box').toggle();
                    $(".reply-text-box-input").focus();
                });
            });
        </script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>IPEC ChatterBox</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap"
        rel="stylesheet">
        <link rel="stylesheet" href="{% static "Homepage/styles.css" %}">
        <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <header class="fixed-header">
            <nav class="navbar">
                <img class="icon" src={% static "Homepage/icon.png" %} alt="">
                <h1>
                    IPEC ChatterBox
                </h1>
            </nav>
            <p>Chat freely without revealing your identity</p>
            <!-- Add other header content as needed -->
        </header>
        <div class="comments-container">
            <ul id="comments-list" class="comments-list">
                {% comment %} {% for user in users %} {% endcomment %}
                {% for message in messages %}
                    <li>
                        <div class="comment-main-level">
                            <!-- Avatar -->
                            <div class="comment-avatar">
                                {% if message.author.gender == 'male' %}
                                    <div class="uid-text-male">#{{ message.author.uid }}</div>
                                {% else %}
                                    <div class="uid-text-female">#{{ message.author.uid }}</div>
                                {% endif %}
                            </div>
                            <!-- Contenedor del Comentario -->
                            <div class="comment-box">
                                <div class="comment-head">
                                    <h6 class="comment-name by-author">
                                        <a href="">Anonymous User #{{ message.author.uid }}</a>
                                    </h6>
                                    <span>{{ message.time }}</span>
                                    <i class="fa fa-reply"></i>
                                    <a href={% url "like" message.id "message" %}> <i class="fa fa-heart">  {{ message.likes }}</i></a>
                                </div>
                                <div class="comment-content" id="m{{ message.id }}">{{ message.text }}</div>
                                {% comment %} Reply Hidden Box {% endcomment %}
                                <div class="reply-text-box" style="display: none;">
                                    <form action="{% url "send_reply" %}" method="post">
                                        {% csrf_token %}
                                        <input class="reply-text-box-input"
                                               type="text"
                                               placeholder="Reply to this message"
                                               name="reply">
                                        <input type="hidden" name="original_message" value="{{ message.id }}">
                                        <button type="submit">Reply</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% for reply in message.reply_set.all %}
                        <ul class="comments-list reply-list">
                            <li>
                                <!-- Avatar -->
                                <div class="comment-avatar">
                                    {% if reply.author.gender == 'male' %}
                                        <div class="uid-text-male-reply">#{{ reply.author.uid }}</div>
                                    {% else %}
                                        <div class="uid-text-female-reply">#{{ reply.author.uid }}</div>
                                    {% endif %}
                                </div>
                                <!-- Contenedor del Comentario -->
                                <div class="comment-box">
                                    <div class="comment-head">
                                        <h6 class="comment-name">
                                            <a href="">Anonymous User #{{ reply.author.uid }}</a>
                                        </h6>
                                        <span>{{ reply.time }}</span>
                                        <a href={% url "like" reply.id "reply" %}> <i class="fa fa-heart">  {{ reply.likes }}</i></a>
                                    </div>
                                    <div class="comment-content" id="r{{ reply.id }}">{{ reply.text }}</div>
                                </div>
                            </li>
                        </ul>
                    {% endfor %}
                {% endfor %}
                {% comment %} {% endfor %} {% endcomment %}
            </ul>
        </div>
        <div id="home"></div>
        <div class="send-message">
            <div class= "message-elements">
                <form action="{% url "send_message" %}" method="post">
                    {% csrf_token %}
                    <input id="text-box"
                           class="text-box"
                           type="text"
                           placeholder="Send your message"
                           name="message">
                    <button type="submit">Post</button>
                </form>
                <a href="#home">
                    <div class="scrolltoBottom">
                        <i class="fa fa-chevron-down"></i>
                    </div>
                </a>
            </div>
        </div>
    </body>
</html>